name: Publish package to GitHub Packages
on:
  release:
    types: [created, edited]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.19.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@enley-es"
      - name: Install dependencies
        run: npm ci
      - name: Install Angular CLI
        run: npm install -g @angular/cli
      - name: Build the package
        run: NODE_OPTIONS=--openssl-legacy-provider ng build
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}